- hosts: localhost
  become: yes
  tasks:
    - name: Install git
      apt: name=git state=present

    - name: Install docker.io
      apt: name=docker.io state=present

    - name: Install virtualbox
      apt: name=virtualbox state=present

    - name: Install tmux
      apt: name=tmux state=present

    - name: Install chromium-browser
      apt: name=chromium-browser state=present

    - name: Install gimp
      apt: name=gimp state=present

    - name: Install mysql-workbench
      apt: name=mysql-workbench state=present

    - name: Install gconf-service-backend
      apt: name=gconf-service-backend state=present

    - name: Install gconf-service
      apt: name=gconf-service state=present

    - name: Install libgconf-2-4
      apt: name=libgconf-2-4 state=present

    - name: Install gconf2-common
      apt: name=gconf2-common state=present

    - name: Install vscode
      shell: |
       wget https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable -O /tmp/code_latest_amd64.deb
       sudo dpkg -i /tmp/code_latest_amd64.deb

    - name: Install apache2  
      apt: name=apache2 state=present

    - name: Install mysql-server
      apt: name=mysql-server state=present
