- hosts: localhost
  become: yes
  tasks:
    - name: Install git
      apt: name=git state=present
    - name: Install apache2  
      apt: name=apache2 state=present
    - name: Install mysql-server
      apt: name=mysql-server state=present
